#%RAML 1.0
title: LearnRAMLSpec
baseUri: http://localhost:8081/studentApi
version: 1.0.0

/createStudentInformation:
  displayName: Create Student Deatils
  description: The method is created for student registration information

  post:
    
  patch:
  
  put:

/retrieveStudentInformation:
  displayName: Retrieve Student Information
  description: This method is created for retrieving the student information from the database.

  get: